# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoClaudeMonitor < Formula
  desc "Claude Code usage monitor and analyzer"
  homepage "https://github.com/penwyp/go-claude-monitor"
  version "0.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/penwyp/go-claude-monitor/releases/download/v0.0.4/go-claude-monitor_0.0.4_darwin_amd64.tar.gz"
      sha256 "de427ecf2cdd050e5a7e000afe6959476467784d0f363f779e2b2712c19af37e"

      def install
        bin.install "go-claude-monitor"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/penwyp/go-claude-monitor/releases/download/v0.0.4/go-claude-monitor_0.0.4_darwin_arm64.tar.gz"
      sha256 "104e70a6d5c0a98933e7f0dbc0f73142271060e64734d9edba8f0e39aaac7ca5"

      def install
        bin.install "go-claude-monitor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/penwyp/go-claude-monitor/releases/download/v0.0.4/go-claude-monitor_0.0.4_linux_amd64.tar.gz"
      sha256 "957f28358f1b14a0a880628c907c05478f343dc2d37333c4705f995afc68e5be"
      def install
        bin.install "go-claude-monitor"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/penwyp/go-claude-monitor/releases/download/v0.0.4/go-claude-monitor_0.0.4_linux_arm64.tar.gz"
      sha256 "115a88fe3f9fb55b0d11ebb946bf251b7174d4edd1765b731502f1261c1e22a7"
      def install
        bin.install "go-claude-monitor"
      end
    end
  end

  test do
    system "#{bin}/go-claude-monitor", "--help"
  end
end
