# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoClaudeMonitor < Formula
  desc "Claude Code usage monitor and analyzer"
  homepage "https://github.com/penwyp/go-claude-monitor"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/penwyp/go-claude-monitor/releases/download/v0.0.2/go-claude-monitor_0.0.2_darwin_amd64.tar.gz"
      sha256 "9fca98b2042018b55a7f1d8af1461d9e6cbfee4860ea2406666840acae474c2c"

      def install
        bin.install "go-claude-monitor"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/penwyp/go-claude-monitor/releases/download/v0.0.2/go-claude-monitor_0.0.2_darwin_arm64.tar.gz"
      sha256 "e49032072ea7baa6ba1f66b57787f9e99786a0d336fb2f77d6d923d2561a39da"

      def install
        bin.install "go-claude-monitor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/penwyp/go-claude-monitor/releases/download/v0.0.2/go-claude-monitor_0.0.2_linux_amd64.tar.gz"
      sha256 "5468964252a4ccfdfeb9d9207074f845fe1d7bfd9b35a8c9d4c61e212cf89c9f"
      def install
        bin.install "go-claude-monitor"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/penwyp/go-claude-monitor/releases/download/v0.0.2/go-claude-monitor_0.0.2_linux_arm64.tar.gz"
      sha256 "aadf78b7931549274eba422ea6342bb93894b8fb0ff837abebf1d8b08d5b6672"
      def install
        bin.install "go-claude-monitor"
      end
    end
  end

  test do
    system "#{bin}/go-claude-monitor", "--help"
  end
end
